#!/bin/bash
set -euo pipefail
SKETCH_DIR="$(dirname "$0")"
arduino-cli compile --fqbn arduino:avr:mega "$SKETCH_DIR"
arduino-cli upload -p /dev/ttyACM0 --fqbn arduino:avr:mega "$SKETCH_DIR"
#arduino-cli monitor -p /dev/ttyACM0 -c baudrate=115200
